### ISSUE TITLE
client/angular error

### ISSUE THREAD

**Issue by adilahmed241** [AmitXShukla/Employee-Payroll-Salary-App-Angular-11-MEAN-Stack#21]
![Screenshot (12)](https://user-images.githubusercontent.com/63300689/99897524-2bc08880-2cab-11eb-83ea-89a7b9abcfd6.png)

**Comment by AmitXShukla** [comment]
I will keep this issue open, will upgrade this repository to Angular 11 now, please expect updated code by Nov 30.

**Comment by Aravind9276** [comment]
Can you update the code today sir?

**Comment by Aravind9276** [comment]
> I will keep this issue open, will upgrade this repository to Angular 11 now, please expect updated code by Nov 30.

Sir can you do it by today?

**Comment by AmitXShukla** [comment]
not today, but will try to finish this by Monday

**Comment by AmitXShukla** [comment]
can you do ng version in your environment ? what Angular version you are using ?

**Comment by Aravind9276** [comment]
No sir it doesnt seem to work.Im having a problem with deploying it.Using angular 11 sir

**Comment by AmitXShukla** [comment]
> No sir it doesnt seem to work.Im having a problem with deploying it.Using angular 11 sir

i'll take a look later this weekend.

**Comment by AmitXShukla** [comment]
Just updated Angular Client code to latest Angular 11.0, don't forget to update tsconfig.json file as well.
